import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import fg from 'fast-glob';
import { readActiveProjectSlug } from '../core/aut/projectPaths';

/**
 * @fileoverview Deletes only the output files generated by Agents 01, 02, 04 and 05, so the
 * pipeline can be re-run from a clean slate without touching inputs, config, memory, or another
 * agent's output.
 *
 * Safe by default: without --yes/--apply this only PRINTS what would be deleted.
 *
 * Usage:
 *   npx ts-node -r ts-node/register cli/clean-agent-outputs.ts            (dry run)
 *   npx ts-node -r ts-node/register cli/clean-agent-outputs.ts --yes      (actually deletes)
 *
 * Explicitly NOT touched, even though it's tempting to lump them in:
 *   - requirements/requirement.md, requirements/uploads/*.md  → inputs to Agent 01, not its output
 *   - reports/json/test-case-review-*.json                    → Agent 03 output (not in scope)
 *   - reports/json/playwright-results.json, junit-results.xml → Agent 07 output (not in scope)
 *   - core/project-memory/memory.json, .state/*               → cross-cycle learning & pipeline state
 *   - tests/pages/BasePage.ts, tests/helpers/env.ts            → hand-written shared framework code
 *   - projects/<slug>/aut-profile.json                        → hand-authored AUT onboarding config
 *   - projects/<slug>/learnings/*.md and each agent's learnings/ folder → accumulated cross-cycle learnings
 *   - tests/projects/<slug>/legacy/*                           → archived files, not written by Agent 05
 *
 * Note: this only removes files on disk. Agent 04/05 read their inputs from the pipeline state
 * (StateManager/SQLite), not from their own prior output files, so deleting these files is enough
 * to force a clean regeneration — it does not also require a state reset (npm run pipeline:reset).
 */

const ROOT = path.resolve(__dirname, '..');

/** Glob patterns (relative to ROOT) for each agent's own generated output — nothing else. */
function targets(): Record<string, string[]> {
  const slug = readActiveProjectSlug();
  const projectGlob = slug ? `tests/projects/${slug}` : 'tests/projects/*';

  return {
    '01-requirement-analyzer': [
      'reports/json/requirement-analysis.json',
    ],
    '02-test-case-generator': [
      `${projectGlob}/features/**/*.feature`,
      'reports/json/test-cases-zephyr-*.json', // only exists when SAVE_ZEPHYR_DISK_JSON=true
    ],
    '04-test-data-generator': [
      'reports/json/test-data-manifest-*.json',
      'reports/json/enriched-test-cases-*.json',
      `${projectGlob}/fixtures/test-data.json`,
    ],
    '05-playwright-script-generator': [
      `${projectGlob}/specs/*.spec.ts`,
      `${projectGlob}/pages/*.ts`,
      `${projectGlob}/page-maps/*.json`,
      `${projectGlob}/k6/*`,
      `${projectGlob}/fixtures/test-data.json`,
      `${projectGlob}/automation-manifest.json`,
    ],
  };
}

async function main(): Promise<void> {
  const apply = process.argv.includes('--yes') || process.argv.includes('--apply');
  const all = targets();

  console.log(apply
    ? chalk.yellow('🗑️  Deleting Agent 01/02/04/05 output files...')
    : chalk.yellow('🔍 DRY RUN — nothing will be deleted. Pass --yes to actually delete.'));

  let total = 0;
  for (const [agentId, patterns] of Object.entries(all)) {
    const matches = await fg(patterns, {
      cwd: ROOT, absolute: true, onlyFiles: true, dot: false,
    });
    if (matches.length === 0) continue;

    console.log(chalk.cyan(`\n[${agentId}] ${matches.length} file(s)`));
    for (const file of matches) {
      console.log(chalk.gray(`  - ${path.relative(ROOT, file)}`));
      if (apply) fs.unlinkSync(file);
    }
    total += matches.length;
  }

  if (total === 0) {
    console.log(chalk.gray('\nNothing to delete.'));
  } else if (apply) {
    console.log(chalk.green(`\n✅ Deleted ${total} file(s).`));
  } else {
    console.log(chalk.yellow(`\n${total} file(s) would be deleted. Re-run with --yes to actually delete.`));
  }
}

main().catch((err) => {
  console.error(chalk.red(err instanceof Error ? err.stack || err.message : String(err)));
  process.exit(1);
});
