'use strict';

/**
 * @fileoverview Swag Labs Login Page Authentication — Playwright UI Automation Spec
 * Generated by ARIA Agent 05 | TC Keys: TC-001, TC-002, TC-003, TC-004, TC-005, TC-006
 * Feature: F-01 | Risk: High
 * @module SwagLabsLoginPageAuthenticationSpec
 */

import { test as base, expect } from '@playwright/test';
import { SwagLabsLoginPageAuthenticationPage } from '../pages/SwagLabsLoginPageAuthenticationPage';
import testData from '../fixtures/test-data.json';

// Reusable fixture injection with TypeScript types
const test = base.extend<{ featurePage: SwagLabsLoginPageAuthenticationPage }>({
  featurePage: async ({ page }, use) => {
    await use(new SwagLabsLoginPageAuthenticationPage(page));
  },
});

test.describe('Swag Labs Login Page Authentication', () => {
  test.beforeEach(async ({ featurePage }) => {
    await featurePage.navigate(testData.baseURL);
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      const sanitizedTitle = testInfo.title.replace(/[^a-zA-Z0-9_-]/g, '_');
      await page.screenshot({
        path: `reports/attachments/screenshots/${sanitizedTitle}-${Date.now()}.png`,
        fullPage: false,
      });
    }
  });

  // ── TC-001: Successful login with standard user redirects to inventory and stores session token ──
  test('TC-001: [POS] Successful login with standard user redirects to inventory and stores session token', {
    tag: ['@positive', '@smoke'],
    annotation: [
      { type: 'TC Key',   description: 'TC-001' },
      { type: 'Feature',  description: 'F-01' },
      { type: 'Priority', description: 'High' },
    ],
  }, async ({ featurePage, page }) => {
    // Verify initial state on page load
    await expect(featurePage.usernameInput).toBeVisible();
    await expect(featurePage.passwordInput).toBeVisible();
    await expect(featurePage.loginButton).toBeVisible();

    // Perform login
    await featurePage.login(testData.standardUsername, testData.password);

    // Verify redirection and catalog visibility
    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();

    // Verify session storage is populated
    const sessionStorageData = await page.evaluate(() => {
      return JSON.stringify(sessionStorage);
    });
    expect(sessionStorageData).not.toBe('{}');
  });

  // ── TC-002: Login with performance glitch user redirects successfully within latency threshold ──
  test('TC-002: [POS] Login with performance glitch user redirects successfully within latency threshold', {
    tag: ['@positive', '@performance'],
    annotation: [
      { type: 'TC Key',   description: 'TC-002' },
      { type: 'Feature',  description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    // Verify initial state on page load
    await expect(featurePage.usernameInput).toBeVisible();
    await expect(featurePage.passwordInput).toBeVisible();
    await expect(featurePage.loginButton).toBeVisible();

    // Measure latency during authentication flow
    const startTime = Date.now();
    await featurePage.login(testData.performanceGlitchUsername, testData.password);
    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();
    const duration = Date.now() - startTime;

    // Assert performance criteria
    expect(duration).toBeGreaterThanOrEqual(1000);
    expect(duration).toBeLessThan(15000); // Rule 10: General performance limit
    expect(duration).toBeLessThan(5000);  // Specific TC requirement: within 5000 ms
  });

  // ── TC-003: Login with problem user displays the same product image for all products ──
  test('TC-003: [POS] Login with problem user displays the same product image for all products', {
    tag: ['@positive', '@visual'],
    annotation: [
      { type: 'TC Key',   description: 'TC-003' },
      { type: 'Feature',  description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    // Verify initial state on page load
    await expect(featurePage.usernameInput).toBeVisible();
    await expect(featurePage.passwordInput).toBeVisible();
    await expect(featurePage.loginButton).toBeVisible();

    // Perform login
    await featurePage.login(testData.problemUsername, testData.password);
    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();

    // Verify visual defect: same product image for all products (sl-404 placeholder)
    const imageSources = await featurePage.getProductImageSources();
    expect(imageSources.length).toBeGreaterThan(0);
    
    const uniqueSources = new Set(imageSources);
    expect(uniqueSources.size).toBe(1);
    expect(imageSources.some(src => src.includes('sl-404'))).toBeTruthy();
  });

  // ── TC-004: Login with error user redirects successfully and displays compromise error dialog ──
  test('TC-004: [POS] Login with error user redirects successfully and displays compromise error dialog', {
    tag: ['@positive', '@error-handling'],
    annotation: [
      { type: 'TC Key',   description: 'TC-004' },
      { type: 'Feature',  description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    // Verify initial state on page load
    await expect(featurePage.usernameInput).toBeVisible();
    await expect(featurePage.passwordInput).toBeVisible();
    await expect(featurePage.loginButton).toBeVisible();

    // Setup dialog listener to capture potential native browser dialog
    let dialogTriggered = false;
    let dialogMessage = '';
    page.on('dialog', async (dialog) => {
      dialogTriggered = true;
      dialogMessage = dialog.message();
      await dialog.dismiss();
    });

    // Perform login
    await featurePage.login(testData.errorUsername, testData.password);
    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();

    // Verify visual defect: same product image for all products (sl-404 placeholder)
    const imageSources = await featurePage.getProductImageSources();
    expect(imageSources.length).toBeGreaterThan(0);
    
    const uniqueSources = new Set(imageSources);
    expect(uniqueSources.size).toBe(1);
    expect(imageSources.some(src => src.includes('sl-404'))).toBeTruthy();

    // Verify dialog message if triggered
    if (dialogTriggered) {
      expect(dialogMessage.toLowerCase()).toContain('compromise');
    }
  });

  // ── TC-005: Login with visual user redirects successfully and displays visual glitch images ──
  test('TC-005: [POS] Login with visual user redirects successfully and displays visual glitch images', {
    tag: ['@positive', '@visual'],
    annotation: [
      { type: 'TC Key',   description: 'TC-005' },
      { type: 'Feature',  description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    // Verify initial state on page load
    await expect(featurePage.usernameInput).toBeVisible();
    await expect(featurePage.passwordInput).toBeVisible();
    await expect(featurePage.loginButton).toBeVisible();

    // Perform login
    await featurePage.login(testData.visualUsername, testData.password);
    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();

    // Verify visual glitch images (all images are identical and point to sl-404 placeholder)
    const imageSources = await featurePage.getProductImageSources();
    expect(imageSources.length).toBeGreaterThan(0);
    
    const uniqueSources = new Set(imageSources);
    expect(uniqueSources.size).toBe(1);
    expect(imageSources.some(src => src.includes('sl-404'))).toBeTruthy();
  });

  // ── TC-006: Login button remains enabled and does not show loading indicator upon click ──
  test('TC-006: [EDGE] Login button remains enabled and does not show loading indicator upon click', {
    tag: ['@edge', '@functional'],
    annotation: [
      { type: 'TC Key',   description: 'TC-006' },
      { type: 'Feature',  description: 'F-01' },
      { type: 'Priority', description: 'Low' },
    ],
  }, async ({ featurePage }) => {
    // Rule 6: Assert initial state on page load before triggering inputs or submissions
    await expect(featurePage.loginButton).toBeVisible();
    await expect(featurePage.loginButton).toBeEnabled();

    // Click login button with empty inputs
    await featurePage.clickLogin();

    // Verify the button remains enabled and does not show loading indicator
    await expect(featurePage.loginButton).toBeEnabled();
    
    const buttonText = await featurePage.loginButton.textContent();
    expect(buttonText?.toLowerCase()).not.toContain('loading');
    expect(buttonText?.toLowerCase()).not.toContain('please wait');
  });

  // ── Batch 2 ──
test('Username field is case sensitive and rejects uppercase standard user username', { annotation: [{ type: 'TC Key', description: 'TC-007' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();

  await featurePage.usernameInput.fill('STANDARD_USER');
  await featurePage.passwordInput.fill(testData.password);
  await featurePage.loginButton.click();

  // Expect to remain on the login page and show error
  await expect(page).toHaveURL(testData.baseURL);
  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toContainText(testData.errorInvalidCredentials);
});

test('Password field masks all entered characters', { annotation: [{ type: 'TC Key', description: 'TC-008' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.passwordInput).toBeVisible();
  
  // Verify the input type is password (which masks characters)
  const inputType = await featurePage.passwordInput.getAttribute('type');
  expect(inputType).toBe('password');

  await featurePage.passwordInput.fill(testData.password);
  await expect(featurePage.passwordInput).toHaveValue(testData.password);
});

test('Locked out user login displays locked out error message below the form', { annotation: [{ type: 'TC Key', description: 'TC-009' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  await featurePage.usernameInput.fill(testData.lockedOutUsername);
  await featurePage.passwordInput.fill(testData.password);
  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toContainText(testData.errorLockedOut);

  // Inspect background color of the error message container
  const errorBgColor = await featurePage.errorMessageContainer.evaluate(el => window.getComputedStyle(el).backgroundColor);
  expect(errorBgColor).toBe('rgb(226, 35, 26)');

  // Assert no error icon is inside the error message container
  await expect(featurePage.errorMessageContainer.locator('.error_icon')).not.toBeVisible();
});

test('Invalid credentials login displays mismatch error message below the form', { annotation: [{ type: 'TC Key', description: 'TC-010' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  await featurePage.usernameInput.fill('invalid_user');
  await featurePage.passwordInput.fill('invalid_password');
  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toContainText(testData.errorInvalidCredentials);

  // Inspect background color of the error message container rather than text font color
  const errorBgColor = await featurePage.errorMessageContainer.evaluate(el => window.getComputedStyle(el).backgroundColor);
  expect(errorBgColor).toBe('rgb(226, 35, 26)');

  // Assert no error icon is inside the error message container
  await expect(featurePage.errorMessageContainer.locator('.error_icon')).not.toBeVisible();
});

test('Submitting empty credentials displays username required error message', { annotation: [{ type: 'TC Key', description: 'TC-011' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  // Ensure fields are empty
  await featurePage.usernameInput.fill('');
  await featurePage.passwordInput.fill('');
  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toContainText('Epic sadface: Username is required');

  const errorBgColor = await featurePage.errorMessageContainer.evaluate(el => window.getComputedStyle(el).backgroundColor);
  expect(errorBgColor).toBe('rgb(226, 35, 26)');

  await expect(featurePage.errorMessageContainer.locator('.error_icon')).not.toBeVisible();
});

test('Submitting empty username with populated password displays username required error message', { annotation: [{ type: 'TC Key', description: 'TC-012' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  await featurePage.usernameInput.fill('');
  await featurePage.passwordInput.fill(testData.password);
  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toContainText('Epic sadface: Username is required');

  const errorBgColor = await featurePage.errorMessageContainer.evaluate(el => window.getComputedStyle(el).backgroundColor);
  expect(errorBgColor).toBe('rgb(226, 35, 26)');

  await expect(featurePage.errorMessageContainer.locator('.error_icon')).not.toBeVisible();
});

  // ── Batch 3 ──
test('Submitting populated username with empty password displays password required error message', { annotation: [{ type: 'TC Key', description: 'TC-013' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  await featurePage.usernameInput.fill(testData.standardUsername);
  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toHaveText(/Epic sadface: Password is required/);

  const bgColor = await featurePage.errorMessageContainer.evaluate((el) => {
    return window.getComputedStyle(el).backgroundColor;
  });
  expect(['rgb(226, 35, 26)', '#e2231a', '#E2231A'].includes(bgColor)).toBeTruthy();
});

test('Error message persists until the page is refreshed', { annotation: [{ type: 'TC Key', description: 'TC-014' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toHaveText(/Epic sadface: Username is required/);

  await page.reload();
  await page.waitForLoadState('domcontentloaded');

  await expect(featurePage.errorMessageContainer).not.toBeVisible();
});

test('Error message persists until the form is resubmitted with different inputs', { annotation: [{ type: 'TC Key', description: 'TC-015' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toHaveText(/Epic sadface: Username is required/);

  await featurePage.usernameInput.fill(testData.standardUsername);
  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toHaveText(/Epic sadface: Password is required/);
});

test('Username with leading and trailing whitespace is trimmed before validation', { annotation: [{ type: 'TC Key', description: 'TC-016' }] }, async ({ featurePage, page }) => {
  await expect(featurePage.usernameInput).toBeVisible();
  await expect(featurePage.passwordInput).toBeVisible();
  await expect(featurePage.loginButton).toBeVisible();

  await featurePage.usernameInput.fill('  locked_out_user  ');
  await featurePage.passwordInput.fill(testData.password);
  await featurePage.loginButton.click();

  await expect(featurePage.errorMessageContainer).toBeVisible();
  await expect(featurePage.errorMessageContainer).toHaveText(testData.errorLockedOut);
});

});