'use strict';

/**
 * @fileoverview Swag Labs Login Authentication & Form Handling — Playwright UI Automation Spec
 * Generated by ARIA Agent 05 | TC Keys: TC-001, TC-002, TC-003, TC-004, TC-005, TC-006
 * Feature: F-01 | Feature Name: Swag Labs Login Authentication & Form Handling
 * @module SwagLabsLoginAuthenticationFormHandlingSpec
 */

import { test as base, expect } from '@playwright/test';
import { SwagLabsLoginAuthenticationFormHandlingPage } from '../pages/SwagLabsLoginAuthenticationFormHandlingPage';
import testData from '../fixtures/test-data.json';

// Reusable fixture injection with TypeScript types
const test = base.extend<{ featurePage: SwagLabsLoginAuthenticationFormHandlingPage }>({
  featurePage: async ({ page }, use) => {
    await use(new SwagLabsLoginAuthenticationFormHandlingPage(page));
  },
});

test.describe('Swag Labs Login Authentication & Form Handling', () => {
  test.beforeEach(async ({ featurePage }) => {
    await featurePage.navigate(testData.baseURL);
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      const sanitizedTitle = testInfo.title.replace(/[^a-zA-Z0-9_-]/g, '_');
      await page.screenshot({
        path: `reports/attachments/screenshots/${sanitizedTitle}-${Date.now()}.png`,
        fullPage: false,
      });
    }
  });

  // ── TC-001: [POS] Standard User Authentication ────────────────────────
  test('[US-01] [POS] User Authentication Test Account Handling — standard_user', {
    tag: ['@positive', '@functional', '@smoke'],
    annotation: [
      { type: 'TC Key', description: 'TC-001' },
      { type: 'Feature', description: 'F-01' },
      { type: 'Priority', description: 'High' },
    ],
  }, async ({ featurePage, page }) => {
    await expect(featurePage.loginButton).toBeEnabled();
    await featurePage.fillUsername(testData.standardUsername);
    await featurePage.fillPassword(testData.password);
    await featurePage.clickLogin();

    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();
  });

  // ── TC-002: [POS] Locked Out User Authentication ─────────────────────
  test('[US-01] [POS] User Authentication Test Account Handling — locked_out_user', {
    tag: ['@positive', '@security', '@functional'],
    annotation: [
      { type: 'TC Key', description: 'TC-002' },
      { type: 'Feature', description: 'F-01' },
      { type: 'Priority', description: 'High' },
    ],
  }, async ({ featurePage, page }) => {
    await expect(featurePage.loginButton).toBeEnabled();
    await featurePage.fillUsername(testData.lockedOutUsername);
    await featurePage.fillPassword(testData.password);
    await featurePage.clickLogin();

    await expect(featurePage.errorMessage).toBeVisible();
    await expect(featurePage.errorMessage).toContainText(testData.errorLockedOut);
    await expect(page).toHaveURL(testData.baseURL);
    await expect(featurePage.loginButton).toBeVisible();
  });

  // ── TC-003: [POS] Performance Glitch User Authentication ─────────────
  test('[US-01] [POS] User Authentication Test Account Handling — performance_glitch_user', {
    tag: ['@positive', '@performance', '@functional'],
    annotation: [
      { type: 'TC Key', description: 'TC-003' },
      { type: 'Feature', description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    await expect(featurePage.loginButton).toBeEnabled();
    await featurePage.fillUsername(testData.performanceGlitchUsername);
    await featurePage.fillPassword(testData.password);

    const startTime = Date.now();
    await featurePage.clickLogin();
    await expect(featurePage.inventoryContainer).toBeVisible();
    const duration = Date.now() - startTime;

    expect(duration).toBeGreaterThanOrEqual(1000);
    expect(duration).toBeLessThan(15000);
    await expect(page).toHaveURL(/.*inventory\.html/);
  });

  // ── TC-004: [POS] Problem User Visual Inconsistencies ──────────────────
  test('[US-01] [POS] User Authentication Test Account Handling — problem_user', {
    tag: ['@positive', '@functional'],
    annotation: [
      { type: 'TC Key', description: 'TC-004' },
      { type: 'Feature', description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    await expect(featurePage.loginButton).toBeEnabled();
    await featurePage.login(testData.problemUsername, testData.password);

    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();

    const imageSources = await featurePage.getProductImageSources();
    expect(imageSources.length).toBeGreaterThan(0);
  });

  // ── TC-005: [POS] Error User Authentication ───────────────────────────
  test('[US-01] [POS] User Authentication Test Account Handling — error_user', {
    tag: ['@positive', '@functional'],
    annotation: [
      { type: 'TC Key', description: 'TC-005' },
      { type: 'Feature', description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    await expect(featurePage.loginButton).toBeEnabled();
    await featurePage.login(testData.errorUsername, testData.password);

    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();
  });

  // ── TC-006: [POS] Visual User Authentication ──────────────────────────
  test('[US-01] [POS] User Authentication Test Account Handling — visual_user', {
    tag: ['@positive', '@functional'],
    annotation: [
      { type: 'TC Key', description: 'TC-006' },
      { type: 'Feature', description: 'F-01' },
      { type: 'Priority', description: 'Medium' },
    ],
  }, async ({ featurePage, page }) => {
    await expect(featurePage.loginButton).toBeEnabled();
    await featurePage.login(testData.visualUsername, testData.password);

    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(featurePage.inventoryContainer).toBeVisible();
  });

  // ── Batch 2 ──
test('TC-007: Session Timeout', { annotation: [{ type: 'TC Key', description: 'TC-007' }] }, async ({ page, featurePage }) => {
  await featurePage.usernameInput.fill(testData.standardUsername);
  await featurePage.passwordInput.fill(testData.password);
  await featurePage.loginButton.click();
  await page.context().clearCookies();
  await page.reload();
  await page.waitForLoadState('domcontentloaded');
  await expect(featurePage.loginContainer).toBeVisible();
});

test('TC-008: Username field alphanumeric validation', { annotation: [{ type: 'TC Key', description: 'TC-008' }] }, async ({ page, featurePage }) => {
  const testUser = 'User_123-abc';
  await featurePage.usernameInput.fill(testUser);
  await expect(featurePage.usernameInput).toHaveValue(testUser);
});

test('TC-009: Password field masking and accessibility', { annotation: [{ type: 'TC Key', description: 'TC-009' }] }, async ({ page, featurePage }) => {
  await featurePage.passwordInput.fill(testData.password);
  await expect(featurePage.passwordInput).toHaveAttribute('type', 'password');
  const snapshot = await page.accessibility.snapshot();
  expect(snapshot).toBeDefined();
});

test('TC-010: Empty form submission error color', { annotation: [{ type: 'TC Key', description: 'TC-010' }] }, async ({ page, featurePage }) => {
  await featurePage.loginButton.click();
  await expect(featurePage.errorMessage).toBeVisible();
  const color = await featurePage.errorMessage.evaluate((el) => getComputedStyle(el).color);
  expect(color).toBe('rgb(226, 35, 26)');
  await page.reload();
  await page.waitForLoadState('domcontentloaded');
  await expect(featurePage.errorMessage).not.toBeVisible();
});

test('TC-011: Password required error message', { annotation: [{ type: 'TC Key', description: 'TC-011' }] }, async ({ page, featurePage }) => {
  await featurePage.usernameInput.fill(testData.standardUsername);
  await featurePage.loginButton.click();
  await expect(featurePage.errorMessage).toContainText('Password is required');
  await page.reload();
  await page.waitForLoadState('domcontentloaded');
  await expect(featurePage.errorMessage).not.toBeVisible();
});

test('TC-012: Login button state and security headers', { annotation: [{ type: 'TC Key', description: 'TC-012' }] }, async ({ page, featurePage }) => {
  const response = await page.goto(testData.baseURL);
  const headers = response?.headers();
  expect(headers).toHaveProperty('content-security-policy');
  await expect(featurePage.loginButton).toBeEnabled();
  await featurePage.loginButton.click();
  await expect(featurePage.loginButton).toBeEnabled();
});

  // ── Batch 3 ──
test('Verify error messages render in red text and persist', { annotation: [{ type: 'TC Key', description: 'TC-013' }] }, async ({ page, featurePage }) => {
  await featurePage.usernameInput.fill('invalid_user');
  await featurePage.passwordInput.fill('wrong_password');
  await featurePage.loginButton.click();
  await expect(featurePage.errorMessage).toBeVisible();
  const color = await featurePage.errorMessage.evaluate((el) => window.getComputedStyle(el).color);
  expect(color).toBe('rgb(226, 35, 26)');
  await expect(featurePage.errorMessage).toBeVisible();
});

test('Verify the login form layout centers properly across responsive viewports', { annotation: [{ type: 'TC Key', description: 'TC-014' }] }, async ({ page, featurePage }) => {
  const viewports = [320, 768, 1024, 2560];
  for (const width of viewports) {
    await page.setViewportSize({ width, height: 800 });
    await page.goto(testData.baseURL);
    await expect(featurePage.loginContainer).toBeVisible();
    const box = await featurePage.loginContainer.boundingBox();
    const viewportSize = page.viewportSize();
    if (box && viewportSize) {
      const centerX = box.x + box.width / 2;
      const expectedCenter = viewportSize.width / 2;
      expect(Math.abs(centerX - expectedCenter)).toBeLessThan(50);
    }
  }
});

});