'use strict';

/**
 * @fileoverview Shared utility functions for Agent 02 — Test Case Generator.
 */

import * as crypto from 'crypto';
import { TC_TYPE, TC_STATUS, AUTOMATION_STATUS, PRIORITY } from './constants';
import { FRAMEWORK_CONFIG } from '../../config/framework.config';
export { parseGherkinToZephyr } from './parsers/GherkinToZephyrParser';

// ── TC Builder ────────────────────────────────────────────────────────────────

/**
 * Constructs a single Zephyr-compatible test case object.
 */
export function buildTC(counter: { value: number }, {
  type, feature, story, name, objective, precondition,
  priority, labels, steps, acIndex, apiDetails, performanceRef,
}) {
  const key = `TC-${String(counter.value++).padStart(3, '0')}`;
  const uniqueName = `[${story.id}] ${sanitizeName(name)}`;
  return {
    key,
    name:             uniqueName,
    objective,
    precondition,
    folder:           buildFolder(feature, story, type),
    status:           TC_STATUS.DRAFT,
    priority,
    labels,
    component:        feature.name,
    owner:            'ARIA-AutoGenerated',
    estimatedTime:    estimateTime(type, steps.length),
    type,
    featureId:        feature.id,
    userStoryId:      story.id,
    testSteps:        steps,
    apiDetails:       apiDetails || null,
    performanceRef:   performanceRef || null,
    automatable:      story.testability !== 'MANUAL_ONLY',
    automationStatus: AUTOMATION_STATUS.NOT_AUTOMATED,
    playwrightSpecRef: null,
    hash:             hashTC(name, steps),
    traceabilityLinks: {
      featureId:                feature.id,
      userStoryId:              story.id,
      acceptanceCriterionIndex: acIndex,
      businessRuleIds:          [],
    },
    createdAt: new Date().toISOString(),
  };
}

// ── Formatting ────────────────────────────────────────────────────────────────

export function buildFolder(feature, story, type) {
  const base = `/${feature.name}`;
  if (type === TC_TYPE.API)         return `${base}/API`;
  if (type === TC_TYPE.PERFORMANCE) return `${base}/Performance`;
  return `${base}/${type}`;
}

export function sanitizeName(name: string): string {
  return name.replace(/[^\w\s\-\[\]()–—:]/g, '').slice(0, 200).trim();
}

export function truncate(str: string, len: number): string {
  return str.length > len ? `${str.slice(0, len - 3)}...` : str;
}

export function estimateTime(type: string, stepCount: number): number {
  const baseMap = { Positive: 120, Negative: 90, Edge: 90, API: 60, Performance: 300 };
  return (baseMap[type] || 120) + stepCount * 15;
}

export function hashTC(name: string, steps: any[]): string {
  const content = name + steps.map((s) => s.description).join('');
  return crypto.createHash('md5').update(content).digest('hex').slice(0, 12);
}

// ── Inference Helpers ─────────────────────────────────────────────────────────

export function inferPrecondition(story, feature): string {
  const parts = ['Application is running and accessible.'];
  if (/auth|login|account/i.test(story.goal))    parts.push('User account exists in the system.');
  if (feature.riskLevel === 'CRITICAL')           parts.push('Test environment is fully provisioned and stable.');
  return parts.join(' ');
}

export function riskToPriority(riskLevel: string): string {
  const map = { CRITICAL: PRIORITY.HIGH, HIGH: PRIORITY.HIGH, MEDIUM: PRIORITY.MEDIUM, LOW: PRIORITY.LOW };
  return map[riskLevel] || PRIORITY.MEDIUM;
}

export function inferLabels(story, type: string): string[] {
  const labels = [TC_TYPE.POSITIVE === type || TC_TYPE.NEGATIVE === type || TC_TYPE.EDGE === type ? 'Functional' : type];
  if (story.testTypes.includes('UI'))           labels.push('UI');
  if (story.testTypes.includes('SECURITY'))     labels.push('Security');
  if (/smoke|critical|login|home/i.test(story.title)) labels.push('Smoke');
  labels.push('Regression');
  return [...new Set(labels)];
}

export function inferHTTPMethod(goal: string): string {
  if (/create|add|register|submit|post/i.test(goal))  return 'POST';
  if (/update|edit|modify|change/i.test(goal))        return 'PUT';
  if (/delete|remove/i.test(goal))                    return 'DELETE';
  if (/partial|patch/i.test(goal))                    return 'PATCH';
  return 'GET';
}

export function inferTestData(ac: string, story): string {
  if (/email/i.test(ac))    return '{{validEmail}}';
  if (/password/i.test(ac)) return '{{validPassword}}';
  if (/name/i.test(ac))     return '{{validName}}';
  if (/phone/i.test(ac))    return '{{validPhone}}';
  if (/date/i.test(ac))     return '{{validDate}}';
  return '{{validTestData}}';
}

export function inferRequestBody(story) {
  if (/login|auth/i.test(story.goal))           return { username: '{{validUsername}}', password: '{{validPassword}}' };
  if (/register|create user/i.test(story.goal)) return { email: '{{validEmail}}', password: '{{validPassword}}', name: '{{validName}}' };
  return { data: '{{validPayload}}' };
}

export function acToAction(ac: string): string {
  return ac.replace(/^(given|when|then|and)\s+/i, '').slice(0, 80);
}

export function acToExpectedResult(ac: string): string {
  if (/should|must|shall/i.test(ac)) return ac;
  return `System confirms: ${ac}`;
}

// ── Summary Builders ──────────────────────────────────────────────────────────

export function buildSummary(testCases, analysis) {
  const byType = {};
  for (const tc of testCases) byType[tc.type] = (byType[tc.type] || 0) + 1;
  return {
    totalTestCases:  testCases.length,
    byType,
    featuresCount:   analysis.totalFeatures,
    storiesCount:    analysis.totalUserStories,
    avgTCsPerStory:  Math.round(testCases.length / Math.max(analysis.totalUserStories, 1)),
    coverageTypes:   Object.keys(byType),
    k6Scenarios:     testCases.filter((tc) => tc.performanceRef).length,
  };
}

export function buildApprovalSummary(output) {
  const z = output.zephyrExport;
  const summary: any = {
    'Total Test Cases':    z.totalTestCases,
    'Positive TCs':        z.byType.positive,
    'Negative TCs':        z.byType.negative,
    'Edge TCs':            z.byType.edge,
    'API TCs':             z.byType.api,
    'Performance TCs':     z.byType.performance,
    'K6 Scenarios':        output.k6ScenarioIndex.length,
    'Format':              'Gherkin BDD Feature Files',
  };

  if (output.featureFilePaths && output.featureFilePaths.length > 0) {
    const uiCount = (z.byType.positive || 0) + (z.byType.negative || 0) + (z.byType.edge || 0);
    const parts = [];
    if (uiCount > 0) parts.push(`${uiCount} UI`);
    if (z.byType.api > 0) parts.push(`${z.byType.api} API`);
    if (z.byType.performance > 0) parts.push(`${z.byType.performance} Perf`);
    summary['Feature Files Synced'] = `${output.featureFilePaths.length} file(s) [${parts.join(', ')}]`;
  }

  return summary;
}

export function buildZephyrExport(analysis, testCases) {
  const byType = (type) => testCases.filter((tc) => tc.type === type);
  const testCycles = analysis.features.map((f) => ({
    name:        `${f.name} — Test Cycle`,
    description: `Auto-generated test cycle for feature: ${f.name}`,
    status:      'Not Started',
    jiraVersionId: null,
    testCaseKeys: testCases
      .filter((tc) => tc.traceabilityLinks.featureId === f.id)
      .map((tc) => tc.key),
  }));
  return {
    version:        '1.0',
    exportedAt:     new Date().toISOString(),
    projectKey:     FRAMEWORK_CONFIG.jira.projectKey,
    totalTestCases: testCases.length,
    byType: {
      positive:    byType(TC_TYPE.POSITIVE).length,
      negative:    byType(TC_TYPE.NEGATIVE).length,
      edge:        byType(TC_TYPE.EDGE).length,
      api:         byType(TC_TYPE.API).length,
      performance: byType(TC_TYPE.PERFORMANCE).length,
    },
    testCases,
    testCycles,
  };
}

export function buildK6ScenarioIndex(testCases, analysis) {
  return testCases
    .filter((tc) => tc.type === TC_TYPE.PERFORMANCE && tc.performanceRef)
    .map((tc) => ({
      tcKey:          tc.key,
      scriptPath:     tc.performanceRef.k6ScriptPath,
      scenario:       tc.performanceRef.scenario,
      targetEndpoint: tc.performanceRef.targetEndpoint,
      featureId:      tc.traceabilityLinks.featureId,
      storyId:        tc.traceabilityLinks.userStoryId,
      vus:            FRAMEWORK_CONFIG.k6.vus,
      duration:       FRAMEWORK_CONFIG.k6.duration,
      thresholds:     FRAMEWORK_CONFIG.k6.thresholds,
    }));
}

import * as fs from 'fs';
import * as path from 'path';

/**
 * Scans every existing feature folder for a .feature file already tied to
 * storyId. feature.name is freely regenerated by the requirement analyzer's
 * LLM call on every run, so it cannot be used as a stable folder identity —
 * only storyId (anchored by the analyzer's prompt schema) stays stable across
 * runs of the same requirement.
 */
function findExistingStoryFolder(featureDir: string, storyId: string): { dir: string; fileName: string } | null {
  if (!fs.existsSync(featureDir)) return null;
  const subDirs = fs.readdirSync(featureDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => path.join(featureDir, d.name));

  for (const dir of subDirs) {
    const match = fs.readdirSync(dir)
      .filter((f) => f.endsWith('.feature'))
      .find((f) => f.includes(storyId));
    if (match) return { dir, fileName: match };
  }
  return null;
}

/**
 * Syncs all generated test cases to BDD .feature file(s).
 * Enforces a strict 1:1 parity between test cases and feature Scenarios.
 * Adds @obsolete tags to test cases that are marked as obsolete.
 */
export function syncFeatureFiles(analysis: any, testCases: any[], logger?: any): string[] {
  const featureDir = path.resolve(__dirname, '../../tests/features');
  if (!fs.existsSync(featureDir)) {
    fs.mkdirSync(featureDir, { recursive: true });
  }

  const fallbackStoryId = analysis?.features?.[0]?.userStories?.[0]?.id || 'US-01';
  const storyGroups = new Map<string, any[]>();

  for (const tc of testCases) {
    const storyId = tc.userStoryId || tc.traceabilityLinks?.userStoryId || fallbackStoryId;
    if (!storyGroups.has(storyId)) {
      storyGroups.set(storyId, []);
    }
    storyGroups.get(storyId)!.push(tc);
  }

  const savedPaths: string[] = [];
  let totalScenariosCount = 0;

  for (const [storyId, storyTCs] of storyGroups.entries()) {
    let matchedFeature: any = null;
    let matchedStory: any = null;

    for (const f of (analysis.features || [])) {
      const s = (f.userStories || []).find((st: any) => st.id === storyId);
      if (s) {
        matchedFeature = f;
        matchedStory = s;
        break;
      }
    }

    if (!matchedFeature && analysis.features?.length > 0) {
      matchedFeature = analysis.features[0];
      matchedStory = matchedFeature.userStories?.[0];
    }

    const featureTitle = matchedFeature?.name || matchedStory?.title || 'User Authentication System';
    const role = matchedStory?.role || 'user of the application';
    const goal = matchedStory?.goal || 'authenticate and use the system securely';
    const benefit = matchedStory?.benefit || 'access protected functionality';

    // Prefer reusing whichever existing folder already holds this story's
    // feature file — feature.name is freely regenerated by the requirement
    // analyzer's LLM call on every run, so it can't be used as a stable
    // folder identity. Only storyId stays stable across runs.
    const existingStoryFolder = findExistingStoryFolder(featureDir, storyId);

    let targetFeatureDir: string;
    if (existingStoryFolder) {
      targetFeatureDir = existingStoryFolder.dir;
    } else {
      const featureFolderName = (matchedFeature?.name || 'General Features')
        .replace(/[\/\\?%*:|"<>]/g, '-')
        .trim();
      targetFeatureDir = path.join(featureDir, featureFolderName);
      if (!fs.existsSync(targetFeatureDir)) {
        fs.mkdirSync(targetFeatureDir, { recursive: true });
      }
    }

    let fileName: string | null = existingStoryFolder?.fileName || null;
    if (!fileName && Array.isArray(analysis.gherkinFeatures)) {
      const gf = analysis.gherkinFeatures.find((g: any) =>
        g.fileName && (g.fileName.includes(storyId) || g.fileName.toLowerCase().includes(storyId.toLowerCase()))
      );
      if (gf?.fileName) {
        fileName = path.basename(gf.fileName);
      }
    }

    if (!fileName && Array.isArray(analysis.featureFilePaths)) {
      const fp = analysis.featureFilePaths.find((p: string) => path.basename(p).includes(storyId));
      if (fp) {
        fileName = path.basename(fp);
      }
    }

    if (!fileName && fs.existsSync(targetFeatureDir)) {
      const existingFiles = fs.readdirSync(targetFeatureDir).filter((f: string) => f.endsWith('.feature'));
      const matchedExisting = existingFiles.find((f: string) => f.includes(storyId));
      if (matchedExisting) {
        fileName = matchedExisting;
      }
    }

    if (!fileName && fs.existsSync(featureDir)) {
      const existingFiles = fs.readdirSync(featureDir).filter((f: string) => f.endsWith('.feature'));
      const matchedExisting = existingFiles.find((f: string) => f.includes(storyId));
      if (matchedExisting) {
        fileName = matchedExisting;
      } else if (existingFiles.length === 1) {
        fileName = existingFiles[0];
      }
    }

    if (!fileName) {
      const slug = (matchedStory?.title || matchedFeature?.name || 'feature')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
      fileName = `${storyId}-${slug}.feature`;
    }

    if (!fileName.endsWith('.feature')) {
      fileName = `${fileName}.feature`;
    }

    const uiTCs = storyTCs.filter((tc: any) =>
      tc.type === TC_TYPE.POSITIVE || tc.type === TC_TYPE.NEGATIVE || tc.type === TC_TYPE.EDGE
    );
    const apiTCs = storyTCs.filter((tc: any) => tc.type === TC_TYPE.API);
    const perfTCs = storyTCs.filter((tc: any) => tc.type === TC_TYPE.PERFORMANCE);

    const baseSlug = fileName.replace(/\.feature$/i, '').replace(/-(api|perf)$/i, '');

    const partitions = [
      { type: 'UI', tcs: uiTCs, suffix: '', titleSuffix: '', bgStep: 'Given the user is on the login page' },
      { type: 'API', tcs: apiTCs, suffix: '-api', titleSuffix: ' — API', bgStep: 'Given the backend API service is available' },
      { type: 'Performance', tcs: perfTCs, suffix: '-perf', titleSuffix: ' — Performance', bgStep: 'Given the application is operational for performance testing' },
    ].filter((p) => p.tcs.length > 0);

    for (const partition of partitions) {
      const partFileName = `${baseSlug}${partition.suffix}.feature`;
      const partFilePath = path.join(targetFeatureDir, partFileName);

      const partFeatureTitle = `${featureTitle}${partition.titleSuffix}`;
      const lines: string[] = [
        `Feature: ${partFeatureTitle}`,
        `  As a ${role},`,
        `  I want to ${goal}`,
        `  So that ${benefit}.`,
        '',
        '  Background:',
        `    ${partition.bgStep}`,
        '',
      ];

      for (const tc of partition.tcs) {
        const tags: string[] = [];
        const typeTag = `@${tc.type.toLowerCase()}`;
        tags.push(typeTag);

        if (Array.isArray(tc.labels)) {
          for (const l of tc.labels) {
            const cleanLabel = `@${String(l).toLowerCase().replace(/[^a-z0-9_-]/g, '')}`;
            if (!tags.includes(cleanLabel)) {
              tags.push(cleanLabel);
            }
          }
        }

        const keyTag = `@${tc.key.toLowerCase()}`;
        if (!tags.includes(keyTag)) {
          tags.push(keyTag);
        }

        // Add obsolete tag if user unchecked this TC
        if (tc.status === 'OBSOLETE' || tc.isObsolete) {
          tags.push('@obsolete');
        }

        let scenarioTitle = tc.name || tc.objective || tc.key;
        if (scenarioTitle.includes('—')) {
          scenarioTitle = scenarioTitle.split('—').slice(1).join('—').trim();
        } else if (scenarioTitle.includes(' - ')) {
          scenarioTitle = scenarioTitle.split(' - ').slice(1).join(' - ').trim();
        } else {
          scenarioTitle = scenarioTitle.replace(/^\[.*?\]\s*/g, '').trim();
        }

        lines.push(`  ${tags.join(' ')}`);
        lines.push(`  Scenario: [${tc.key}] ${scenarioTitle}`);

        const steps = tc.testSteps || [];
        if (steps.length === 0) {
          lines.push('    Given the application state is prepared');
          lines.push(`    When the test action for "${tc.key}" is executed`);
          lines.push(`    Then the expected outcome is validated: ${tc.objective || 'Success'}`);
        } else {
          for (let stepIdx = 0; stepIdx < steps.length; stepIdx++) {
            const step = steps[stepIdx];
            const desc = (step.description || '').trim();
            const data = (step.testData || '').trim();
            const expected = (step.expectedResult || '').trim();

            const isVerification = /^(verify|validate|check|confirm|ensure)/i.test(desc);
            const isNav = /^(navigate|open|given|go to)/i.test(desc);

            if (isVerification) {
              const thenText = expected || desc;
              lines.push(`    Then ${thenText}`);
            } else {
              const keyword = step.keyword || ((stepIdx === 0 && isNav) ? 'Given' : 'When');
              lines.push(`    ${keyword} ${desc}`);

              if (data && !/^\((leave blank|none|no token.*)\)$/i.test(data)) {
                lines.push(`    And with test data "${data}"`);
              }

              if (expected && expected.toLowerCase() !== desc.toLowerCase()) {
                lines.push(`    Then ${expected}`);
              }
            }
          }
        }

        lines.push('');
      }

      const content = lines.join('\n');
      fs.writeFileSync(partFilePath, content, 'utf-8');
      savedPaths.push(partFilePath);

      const scenarioCount = (content.match(/^\s*Scenario:/gm) || []).length;
      totalScenariosCount += scenarioCount;

      if (logger) {
        logger.info(`Feature file synced: [${partition.type}]`, {
          filePath: partFilePath,
          storyId,
          scenariosCount: scenarioCount,
          expectedTCs: partition.tcs.length,
        });
      }
    }
  }

  if (logger) {
    if (totalScenariosCount !== testCases.length) {
      logger.warn(`Feature file scenario count mismatch: generated ${totalScenariosCount} scenarios for ${testCases.length} test cases`);
    } else {
      logger.info(`Feature file sync complete: ${totalScenariosCount}/${testCases.length} scenarios strictly matched.`);
    }
  }

  return savedPaths;
}

export interface GherkinStepLine {
  keyword: 'Given' | 'When' | 'Then' | 'And' | 'But';
  text: string;
}

/**
 * Converts a test case's testSteps array into formal Gherkin step lines
 * matching the format generated and saved in Cucumber .feature files.
 */
export function convertTestStepsToGherkin(tc: any): GherkinStepLine[] {
  const steps = tc?.testSteps || [];
  const result: GherkinStepLine[] = [];

  if (steps.length === 0) {
    result.push({ keyword: 'Given', text: 'the application state is prepared' });
    result.push({ keyword: 'When', text: `the test action for "${tc?.key || 'TC'}" is executed` });
    result.push({ keyword: 'Then', text: `the expected outcome is validated: ${tc?.objective || 'Success'}` });
    return result;
  }

  for (let stepIdx = 0; stepIdx < steps.length; stepIdx++) {
    const step = steps[stepIdx];
    const desc = (step.description || '').trim();
    const data = (step.testData || '').trim();
    const expected = (step.expectedResult || '').trim();

    const isVerification = /^(verify|validate|check|confirm|ensure)/i.test(desc);
    const isNav = /^(navigate|open|given|go to)/i.test(desc);

    if (isVerification) {
      const thenText = expected || desc;
      result.push({ keyword: 'Then', text: thenText });
    } else {
      const keyword = (stepIdx === 0 && isNav) ? 'Given' : (step.keyword || 'When');
      result.push({ keyword: keyword as any, text: desc });

      if (data && !/^\((leave blank|none|no token.*)\)$/i.test(data)) {
        result.push({ keyword: 'And', text: `with test data "${data}"` });
      }

      if (expected && expected.toLowerCase() !== desc.toLowerCase()) {
        result.push({ keyword: 'Then', text: expected });
      }
    }
  }

  return result;
}

/**
 * Builds the complete Gherkin Feature Scenario text for a test case
 * as saved in the Cucumber .feature file.
 */
export function buildGherkinScenarioText(tc: any): string {
  const tags: string[] = [];
  if (tc.type) tags.push(`@${tc.type.toLowerCase()}`);
  if (Array.isArray(tc.labels)) {
    for (const l of tc.labels) {
      const clean = `@${String(l).toLowerCase().replace(/[^a-z0-9_-]/g, '')}`;
      if (!tags.includes(clean)) tags.push(clean);
    }
  }
  if (tc.key) tags.push(`@${tc.key.toLowerCase()}`);
  if (tc.status === 'OBSOLETE' || tc.isObsolete) tags.push('@obsolete');

  let scenarioTitle = tc.name || tc.objective || tc.key;
  if (scenarioTitle.includes('—')) {
    scenarioTitle = scenarioTitle.split('—').slice(1).join('—').trim();
  } else if (scenarioTitle.includes(' - ')) {
    scenarioTitle = scenarioTitle.split(' - ').slice(1).join(' - ').trim();
  } else {
    scenarioTitle = scenarioTitle.replace(/^\[.*?\]\s*/g, '').trim();
  }

  const gherkinSteps = convertTestStepsToGherkin(tc);
  const stepLines = gherkinSteps.map((s) => `    ${s.keyword} ${s.text}`);

  return [
    `  ${tags.join(' ')}`,
    `  Scenario: [${tc.key}] ${scenarioTitle}`,
    ...stepLines,
  ].join('\n');
}
