'use strict';

/**
 * @fileoverview Shared utility functions for Agent 02 — Test Case Generator.
 */

import * as crypto from 'crypto';
import { TC_TYPE, TC_STATUS, AUTOMATION_STATUS, PRIORITY } from './constants';
import { FRAMEWORK_CONFIG } from '../../config/framework.config';
export { parseGherkinToZephyr } from './parsers/GherkinToZephyrParser';

// ── TC Builder ────────────────────────────────────────────────────────────────

/**
 * Constructs a single Zephyr-compatible test case object.
 */
export function buildTC(counter: { value: number }, {
  type, feature, story, name, objective, precondition,
  priority, labels, steps, acIndex, apiDetails, performanceRef,
}) {
  const key = `TC-${String(counter.value++).padStart(3, '0')}`;
  const uniqueName = `[${story.id}] ${sanitizeName(name)}`;
  return {
    key,
    name:             uniqueName,
    objective,
    precondition,
    folder:           buildFolder(feature, story, type),
    status:           TC_STATUS.DRAFT,
    priority,
    labels,
    component:        feature.name,
    owner:            'ARIA-AutoGenerated',
    estimatedTime:    estimateTime(type, steps.length),
    type,
    featureId:        feature.id,
    userStoryId:      story.id,
    testSteps:        steps,
    apiDetails:       apiDetails || null,
    performanceRef:   performanceRef || null,
    automatable:      story.testability !== 'MANUAL_ONLY',
    automationStatus: AUTOMATION_STATUS.NOT_AUTOMATED,
    playwrightSpecRef: null,
    hash:             hashTC(name, steps),
    traceabilityLinks: {
      featureId:                feature.id,
      userStoryId:              story.id,
      acceptanceCriterionIndex: acIndex,
      businessRuleIds:          [],
    },
    createdAt: new Date().toISOString(),
  };
}

// ── Formatting ────────────────────────────────────────────────────────────────

export function buildFolder(feature, story, type) {
  const base = `/${feature.name}`;
  if (type === TC_TYPE.API)         return `${base}/API`;
  if (type === TC_TYPE.PERFORMANCE) return `${base}/Performance`;
  return `${base}/${type}`;
}

export function sanitizeName(name: string): string {
  return name.replace(/[^\w\s\-\[\]()–—:]/g, '').slice(0, 200).trim();
}

export function truncate(str: string, len: number): string {
  return str.length > len ? `${str.slice(0, len - 3)}...` : str;
}

export function estimateTime(type: string, stepCount: number): number {
  const baseMap = { Positive: 120, Negative: 90, Edge: 90, API: 60, Performance: 300 };
  return (baseMap[type] || 120) + stepCount * 15;
}

export function hashTC(name: string, steps: any[]): string {
  const content = name + steps.map((s) => s.description).join('');
  return crypto.createHash('md5').update(content).digest('hex').slice(0, 12);
}

// ── Inference Helpers ─────────────────────────────────────────────────────────

export function inferPrecondition(story, feature): string {
  const parts = ['Application is running and accessible.'];
  if (/auth|login|account/i.test(story.goal))    parts.push('User account exists in the system.');
  if (feature.riskLevel === 'CRITICAL')           parts.push('Test environment is fully provisioned and stable.');
  return parts.join(' ');
}

export function riskToPriority(riskLevel: string): string {
  const map = { CRITICAL: PRIORITY.HIGH, HIGH: PRIORITY.HIGH, MEDIUM: PRIORITY.MEDIUM, LOW: PRIORITY.LOW };
  return map[riskLevel] || PRIORITY.MEDIUM;
}

export function inferLabels(story, type: string): string[] {
  const labels = [TC_TYPE.POSITIVE === type || TC_TYPE.NEGATIVE === type || TC_TYPE.EDGE === type ? 'Functional' : type];
  if (story.testTypes.includes('UI'))           labels.push('UI');
  if (story.testTypes.includes('SECURITY'))     labels.push('Security');
  if (/smoke|critical|login|home/i.test(story.title)) labels.push('Smoke');
  labels.push('Regression');
  return [...new Set(labels)];
}

export function inferHTTPMethod(goal: string): string {
  if (/create|add|register|submit|post/i.test(goal))  return 'POST';
  if (/update|edit|modify|change/i.test(goal))        return 'PUT';
  if (/delete|remove/i.test(goal))                    return 'DELETE';
  if (/partial|patch/i.test(goal))                    return 'PATCH';
  return 'GET';
}

export function inferTestData(ac: string, story): string {
  if (/email/i.test(ac))    return '{{validEmail}}';
  if (/password/i.test(ac)) return '{{validPassword}}';
  if (/name/i.test(ac))     return '{{validName}}';
  if (/phone/i.test(ac))    return '{{validPhone}}';
  if (/date/i.test(ac))     return '{{validDate}}';
  return '{{validTestData}}';
}

export function inferRequestBody(story) {
  if (/login|auth/i.test(story.goal))           return { username: '{{validUsername}}', password: '{{validPassword}}' };
  if (/register|create user/i.test(story.goal)) return { email: '{{validEmail}}', password: '{{validPassword}}', name: '{{validName}}' };
  return { data: '{{validPayload}}' };
}

export function acToAction(ac: string): string {
  return ac.replace(/^(given|when|then|and)\s+/i, '').slice(0, 80);
}

export function acToExpectedResult(ac: string): string {
  if (/should|must|shall/i.test(ac)) return ac;
  return `System confirms: ${ac}`;
}

// ── Summary Builders ──────────────────────────────────────────────────────────

export function buildSummary(testCases, analysis) {
  const byType = {};
  for (const tc of testCases) byType[tc.type] = (byType[tc.type] || 0) + 1;
  return {
    totalTestCases:  testCases.length,
    byType,
    featuresCount:   analysis.totalFeatures,
    storiesCount:    analysis.totalUserStories,
    avgTCsPerStory:  Math.round(testCases.length / Math.max(analysis.totalUserStories, 1)),
    coverageTypes:   Object.keys(byType),
    k6Scenarios:     testCases.filter((tc) => tc.performanceRef).length,
  };
}

export function buildApprovalSummary(output) {
  const z = output.zephyrExport;
  const summary: any = {
    'Total Test Cases':    z.totalTestCases,
    'Positive TCs':        z.byType.positive,
    'Negative TCs':        z.byType.negative,
    'Edge TCs':            z.byType.edge,
    'API TCs':             z.byType.api,
    'Performance TCs':     z.byType.performance,
    'K6 Scenarios':        output.k6ScenarioIndex.length,
    'Format':              'Gherkin BDD Feature Files',
  };

  if (output.featureFilePaths && output.featureFilePaths.length > 0) {
    const uiCount = (z.byType.positive || 0) + (z.byType.negative || 0) + (z.byType.edge || 0);
    const parts = [];
    if (uiCount > 0) parts.push(`${uiCount} UI`);
    if (z.byType.api > 0) parts.push(`${z.byType.api} API`);
    if (z.byType.performance > 0) parts.push(`${z.byType.performance} Perf`);
    summary['Feature Files Synced'] = `${output.featureFilePaths.length} file(s) [${parts.join(', ')}]`;
  }

  return summary;
}

export function buildZephyrExport(analysis, testCases) {
  const byType = (type) => testCases.filter((tc) => tc.type === type);
  const testCycles = analysis.features.map((f) => ({
    name:        `${f.name} — Test Cycle`,
    description: `Auto-generated test cycle for feature: ${f.name}`,
    status:      'Not Started',
    jiraVersionId: null,
    testCaseKeys: testCases
      .filter((tc) => tc.traceabilityLinks.featureId === f.id)
      .map((tc) => tc.key),
  }));
  return {
    version:        '1.0',
    exportedAt:     new Date().toISOString(),
    projectKey:     FRAMEWORK_CONFIG.jira.projectKey,
    totalTestCases: testCases.length,
    byType: {
      positive:    byType(TC_TYPE.POSITIVE).length,
      negative:    byType(TC_TYPE.NEGATIVE).length,
      edge:        byType(TC_TYPE.EDGE).length,
      api:         byType(TC_TYPE.API).length,
      performance: byType(TC_TYPE.PERFORMANCE).length,
    },
    testCases,
    testCycles,
  };
}

export function buildK6ScenarioIndex(testCases, analysis) {
  return testCases
    .filter((tc) => tc.type === TC_TYPE.PERFORMANCE && tc.performanceRef)
    .map((tc) => ({
      tcKey:          tc.key,
      scriptPath:     tc.performanceRef.k6ScriptPath,
      scenario:       tc.performanceRef.scenario,
      targetEndpoint: tc.performanceRef.targetEndpoint,
      featureId:      tc.traceabilityLinks.featureId,
      storyId:        tc.traceabilityLinks.userStoryId,
      vus:            FRAMEWORK_CONFIG.k6.vus,
      duration:       FRAMEWORK_CONFIG.k6.duration,
      thresholds:     FRAMEWORK_CONFIG.k6.thresholds,
    }));
}
