'use strict';

/**
 * @fileoverview SwagLabsLoginPageAuthentication Page Object Model
 * Generated by ARIA Agent 05 | Feature: F-01
 * @module SwagLabsLoginPageAuthenticationPage
 */

import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

export class SwagLabsLoginPageAuthenticationPage extends BasePage {
  constructor(page: Page) {
    super(page);
  }

  // ── Locators ───────────────────────────────────────────────────────────
  get usernameInput(): Locator {
    return this.page.locator('[data-test="username"]');
  }

  get passwordInput(): Locator {
    return this.page.locator('[data-test="password"]');
  }

  get loginButton(): Locator {
    return this.page.locator('[data-test="login-button"]');
  }

  get errorMessageContainer(): Locator {
    return this.page.locator('[data-test="error"]');
  }

  get errorIcon(): Locator {
    return this.page.locator('.error_icon');
  }

  get inventoryContainer(): Locator {
    return this.page.locator('[data-test="inventory-container"]').first();
  }

  get productImages(): Locator {
    return this.page.locator('.inventory_item_img img');
  }

  // ── Action Methods ─────────────────────────────────────────────────────
  
  /**
   * Navigates to the specified URL.
   * @param url The application base URL.
   */
  async navigate(url: string): Promise<void> {
    await this.page.goto(url);
  }

  /**
   * Enters the username into the username field.
   * @param username The username string.
   */
  async fillUsername(username: string): Promise<void> {
    await this.usernameInput.fill(username);
  }

  /**
   * Enters the password into the password field.
   * @param password The password string.
   */
  async fillPassword(password: string): Promise<void> {
    await this.passwordInput.fill(password);
  }

  /**
   * Clicks the login button.
   */
  async clickLogin(): Promise<void> {
    await this.loginButton.click();
  }

  /**
   * Performs a complete login flow.
   * @param username The username string.
   * @param password The password string.
   */
  async login(username: string, password: string): Promise<void> {
    await this.fillUsername(username);
    await this.fillPassword(password);
    await this.clickLogin();
  }

  /**
   * Retrieves the 'src' attribute values of all product images in the catalog.
   * Useful for verifying visual inconsistencies or duplicate placeholder images.
   */
  async getProductImageSources(): Promise<string[]> {
    return this.productImages.evaluateAll((images: HTMLImageElement[]) =>
      images.map((img) => img.src)
    );
  }

  /**
   * Retrieves the computed background color of the error message container.
   * Normalizes the returned color value to ensure resilient assertions.
   */
  async getErrorMessageBackground(): Promise<string> {
    return this.errorMessageContainer.evaluate((el) => {
      const container = el.closest('.error-message-container') || el.parentElement || el;
      return window.getComputedStyle(container).backgroundColor;
    });
  }
}