'use strict';

/**
 * @fileoverview Swag Labs Login Authentication & Form Handling Page Object Model
 * Generated by ARIA Agent 05 | Feature: F-01
 * @module SwagLabsLoginAuthenticationFormHandlingPage
 */

import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

export class SwagLabsLoginAuthenticationFormHandlingPage extends BasePage {
  constructor(page: Page) {
    super(page);
  }

  // ── Locators (Strictly 1:1 Unique Selectors with Locator Return Type) ──

  get usernameInput(): Locator {
    return this.page.locator('[data-test="username"]');
  }

  get passwordInput(): Locator {
    return this.page.locator('[data-test="password"]');
  }

  get loginButton(): Locator {
    return this.page.locator('[data-test="login-button"]');
  }

  get errorMessage(): Locator {
    return this.page.locator('[data-test="error"]');
  }

  get errorButton(): Locator {
    return this.page.locator('[data-test="error-button"]');
  }

  get errorMessageContainer(): Locator {
    return this.page.locator('.error-message-container');
  }

  get inventoryContainer(): Locator {
    return this.page.locator('[data-test="inventory-container"]');
  }

  get inventoryList(): Locator {
    return this.page.locator('[data-test="inventory-list"]');
  }

  get inventoryItemImages(): Locator {
    return this.page.locator('.inventory_item_img img');
  }

  get loginLogo(): Locator {
    return this.page.locator('.login_logo');
  }

  get loginContainer(): Locator {
    return this.page.locator('.login_container');
  }

  // ── Action Primitives (Strictly No Assertions) ──

  async navigate(url: string): Promise<void> {
    await this.page.goto(url);
  }

  async fillUsername(username: string): Promise<void> {
    await this.usernameInput.fill(username);
  }

  async fillPassword(password: string): Promise<void> {
    await this.passwordInput.fill(password);
  }

  async clickLogin(): Promise<void> {
    await this.loginButton.click();
  }

  async login(username: string, password: string): Promise<void> {
    await this.fillUsername(username);
    await this.fillPassword(password);
    await this.clickLogin();
  }

  async clearUsername(): Promise<void> {
    await this.usernameInput.clear();
  }

  async clearPassword(): Promise<void> {
    await this.passwordInput.clear();
  }

  async dismissErrorMessage(): Promise<void> {
    await this.errorButton.click();
  }

  async getProductImageSources(): Promise<string[]> {
    const images = this.inventoryItemImages;
    const count = await images.count();
    const sources: string[] = [];
    for (let i = 0; i < count; i++) {
      const src = await images.nth(i).getAttribute('src');
      if (src) {
        sources.push(src);
      }
    }
    return sources;
  }
}