'use strict';

/**
 * @fileoverview Swag Labs Authentication System Page Object Model
 * Generated by ARIA Agent 05 | Feature: F-01
 * @module SwagLabsAuthenticationSystemPage
 */

import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

export class SwagLabsAuthenticationSystemPage extends BasePage {
  constructor(page: Page) {
    super(page);
  }

  // ── Locators ─────────────────────────────────────────────────────────────
  get usernameInput(): Locator {
    return this.page.locator('[data-test="username"]');
  }

  get passwordInput(): Locator {
    return this.page.locator('[data-test="password"]');
  }

  get loginButton(): Locator {
    return this.page.locator('[data-test="login-button"]');
  }

  get errorMessage(): Locator {
    return this.page.locator('[data-test="error"]');
  }

  get errorMessageContainer(): Locator {
    return this.page.locator('.error-message-container');
  }

  get errorButton(): Locator {
    return this.page.locator('[data-test="error-button"]');
  }

  get inventoryContainer(): Locator {
    return this.page.locator('[data-test="inventory-container"]').first();
  }

  get loginLogo(): Locator {
    return this.page.locator('.login_logo');
  }

  get loginCredentialsContainer(): Locator {
    return this.page.locator('[data-test="login-credentials-container"]');
  }

  get loginPasswordContainer(): Locator {
    return this.page.locator('[data-test="login-password-container"]');
  }

  get loginWrapper(): Locator {
    return this.page.locator('.login_wrapper');
  }

  // ── Action Primitives (Strictly No Assertions in POM) ────────────────────
  async navigate(url: string): Promise<void> {
    await this.page.goto(url, { waitUntil: 'domcontentloaded' });
  }

  async fillUsername(username: string): Promise<void> {
    await this.usernameInput.fill(username);
  }

  async fillPassword(password: string): Promise<void> {
    await this.passwordInput.fill(password);
  }

  async clickLogin(): Promise<void> {
    await this.loginButton.click();
  }

  async login(username: string, password: string): Promise<void> {
    await this.fillUsername(username);
    await this.fillPassword(password);
    await this.clickLogin();
  }

  async clearUsername(): Promise<void> {
    await this.usernameInput.clear();
  }

  async clearPassword(): Promise<void> {
    await this.passwordInput.clear();
  }

  async dismissError(): Promise<void> {
    await this.errorButton.click();
  }
}
export default SwagLabsAuthenticationSystemPage;